resources:
  - manager.yaml
vars:
  - name: OPERATOR_DEPLOYMENT_NAME
    objref:
      kind: Deployment
      name: controller-manager
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.name
