# permissions for end users to view webhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mailgun-operator
    app.kubernetes.io/managed-by: kustomize
  name: domain-webhook-viewer-role
rules:
- apiGroups:
  - domain.mailgun.com
  resources:
  - webhooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domain.mailgun.com
  resources:
  - webhooks/status
  verbs:
  - get
