# permissions for end users to edit routes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mailgun-operator
    app.kubernetes.io/managed-by: kustomize
  name: domain-route-editor-role
rules:
- apiGroups:
  - domain.mailgun.com
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - domain.mailgun.com
  resources:
  - routes/status
  verbs:
  - get
