---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - domain.mailgun.com
  resources:
  - domains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - domain.mailgun.com
  resources:
  - domains/finalizers
  verbs:
  - update
- apiGroups:
  - domain.mailgun.com
  resources:
  - domains/status
  verbs:
  - get
  - patch
  - update
