apiVersion: domain.mailgun.com/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: mailgun-operator
    app.kubernetes.io/managed-by: kustomize
  name: route-sample
spec:
  # TODO(user): Add fields here
